on:
  workflow_dispatch:
    inputs:
      compodoc:
        description: 'Build and deploy compodoc?'
        required: false
        type: boolean
      what_version:
        description: 'What is the release version? (e.g. 5.0.1)'
        required: true

name: Pre-release for Spartacus

jobs:
  publish_compodoc:
    name: Deploy compodocs to github
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate and publish compodocs
        if: ${{ github.event.inputs.compodoc == 'true' }}
        run: |
          git remote set-url origin https://git:${{ secrets.GH_TEMPORARY_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
  
          yarn generate:publish:docs -- -u "github-actions-bot <support+actions@github.com>"
  tag_sampledata:
    name: Tagging sample data
    runs-on: ubuntu-latest
    steps:
      - name: Determine major version
        env:
          SPARTACUS_VERSION: ${{ github.event.inputs.what_version }}
        id: current-run-major-version
        run: echo "MAJOR_VERSION=${SPARTACUS_VERSION%%.*}" >> $GITHUB_OUTPUT
      - name: Tagging the branch of release/${{ steps.current-run-major-version.outputs.MAJOR_VERSION}}.x
        uses: actions/checkout@v3
        with:
          github-server-url: 'https://github.tools.sap'
          repository: 'cx-commerce/spartacussampledata'
          token: ${{ secrets.GHT_PRIVATE_REPO_TOKEN }}
          ref: 'release/${{ steps.current-run-major-version.outputs.MAJOR_VERSION}}.x'
      - name: push the tag to the repository
        run: |
          git tag ${{ github.event.inputs.what_version }}
          git push origin --tags
  publish_sample_data: 
    name: Publishing Spartacus Sample Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: create release with sample data assets
        env:
          GHT_USER: ${{ secrets.GHT_USER }}
          GHT_PRIVATE_REPO_TOKEN: ${{ secrets.GHT_PRIVATE_REPO_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TEMPORARY_TOKEN }}
        run: |
          ci-scripts/publish-sample-data.sh
